package com.ssm.mapper;

import com.ssm.bean.Card;
import com.ssm.bean.CardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int countByExample(CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int deleteByExample(CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int deleteByPrimaryKey(Long readerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int insert(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int insertSelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    List<Card> selectByExample(CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    Card selectByPrimaryKey(Long readerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int updateByExampleSelective(@Param("record") Card record, @Param("example") CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int updateByExample(@Param("record") Card record, @Param("example") CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int updateByPrimaryKeySelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int updateByPrimaryKey(Card record);
}