package com.ssm.mapper;

import com.ssm.bean.Clazz;
import com.ssm.bean.ClazzExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClazzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int countByExample(ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int deleteByExample(ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int deleteByPrimaryKey(Integer clazzId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int insert(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int insertSelective(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    List<Clazz> selectByExample(ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    Clazz selectByPrimaryKey(Integer clazzId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int updateByExampleSelective(@Param("record") Clazz record, @Param("example") ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int updateByExample(@Param("record") Clazz record, @Param("example") ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int updateByPrimaryKeySelective(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int updateByPrimaryKey(Clazz record);
}