package com.ssm.mapper;

import com.ssm.bean.Reader;
import com.ssm.bean.ReaderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int countByExample(ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int deleteByExample(ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int deleteByPrimaryKey(Long readId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int insert(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int insertSelective(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    List<Reader> selectByExample(ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    Reader selectByPrimaryKey(Long readId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int updateByExampleSelective(@Param("record") Reader record, @Param("example") ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int updateByExample(@Param("record") Reader record, @Param("example") ReaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int updateByPrimaryKeySelective(Reader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reader
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    int updateByPrimaryKey(Reader record);
}