package com.ssm.bean;

import java.math.BigDecimal;
import java.util.Date;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_id
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    private Long bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.name
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.author
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.publish
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    private String publish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.ISBN
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    private String isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.language
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.price
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.pub_date
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    private Date pubDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.clazz_id
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    private Integer clazzId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.number
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.introduction
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_id
     *
     * @return the value of t_book.book_id
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_id
     *
     * @param bookId the value for t_book.book_id
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.name
     *
     * @return the value of t_book.name
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.name
     *
     * @param name the value for t_book.name
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.author
     *
     * @return the value of t_book.author
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.author
     *
     * @param author the value for t_book.author
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.publish
     *
     * @return the value of t_book.publish
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public String getPublish() {
        return publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.publish
     *
     * @param publish the value for t_book.publish
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public void setPublish(String publish) {
        this.publish = publish == null ? null : publish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.ISBN
     *
     * @return the value of t_book.ISBN
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.ISBN
     *
     * @param isbn the value for t_book.ISBN
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.language
     *
     * @return the value of t_book.language
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.language
     *
     * @param language the value for t_book.language
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.price
     *
     * @return the value of t_book.price
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.price
     *
     * @param price the value for t_book.price
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.pub_date
     *
     * @return the value of t_book.pub_date
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public Date getPubDate() {
        return pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.pub_date
     *
     * @param pubDate the value for t_book.pub_date
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public void setPubDate(Date pubDate) {
        this.pubDate = pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.clazz_id
     *
     * @return the value of t_book.clazz_id
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public Integer getClazzId() {
        return clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.clazz_id
     *
     * @param clazzId the value for t_book.clazz_id
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public void setClazzId(Integer clazzId) {
        this.clazzId = clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.number
     *
     * @return the value of t_book.number
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.number
     *
     * @param number the value for t_book.number
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.introduction
     *
     * @return the value of t_book.introduction
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.introduction
     *
     * @param introduction the value for t_book.introduction
     *
     * @mbggenerated Fri Aug 12 20:58:47 CST 2022
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    public Book() {
    }

    public Book(String name, String author, String publish, String isbn, String language, BigDecimal price, Date pubDate, Integer clazzId, Integer number, String introduction) {
        this.name = name;
        this.author = author;
        this.publish = publish;
        this.isbn = isbn;
        this.language = language;
        this.price = price;
        this.pubDate = pubDate;
        this.clazzId = clazzId;
        this.number = number;
        this.introduction = introduction;
    }

    public Book(Long bookId, String name, String author, String publish, String isbn, String language, BigDecimal price, Date pubDate, Integer clazzId, Integer number, String introduction) {
        this.bookId = bookId;
        this.name = name;
        this.author = author;
        this.publish = publish;
        this.isbn = isbn;
        this.language = language;
        this.price = price;
        this.pubDate = pubDate;
        this.clazzId = clazzId;
        this.number = number;
        this.introduction = introduction;
    }

    @Override
    public String toString() {
        return "Book{" +
                "bookId=" + bookId +
                ", name='" + name + '\'' +
                ", author='" + author + '\'' +
                ", publish='" + publish + '\'' +
                ", isbn='" + isbn + '\'' +
                ", language='" + language + '\'' +
                ", price=" + price +
                ", pubDate=" + pubDate +
                ", clazzId=" + clazzId +
                ", number=" + number +
                ", introduction='" + introduction + '\'' +
                '}';
    }
}