package com.ssm.bean;

public class Card {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.reader_id
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    private Long readerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.username
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.password
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.reader_id
     *
     * @return the value of t_card.reader_id
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public Long getReaderId() {
        return readerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.reader_id
     *
     * @param readerId the value for t_card.reader_id
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public void setReaderId(Long readerId) {
        this.readerId = readerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.username
     *
     * @return the value of t_card.username
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.username
     *
     * @param username the value for t_card.username
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.password
     *
     * @return the value of t_card.password
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.password
     *
     * @param password the value for t_card.password
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    public Card() {
    }

    public Card(String username, String password) {
        this.username = username;
        this.password = password;
    }

    public Card(Long readerId, String username, String password) {
        this.readerId = readerId;
        this.username = username;
        this.password = password;
    }

    @Override
    public String toString() {
        return "Card{" +
                "readerId=" + readerId +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                '}';
    }
}