package com.ssm.bean;

public class Clazz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clazz.clazz_id
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    private Integer clazzId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clazz.clazz_name
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    private String clazzName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clazz.clazz_id
     *
     * @return the value of t_clazz.clazz_id
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public Integer getClazzId() {
        return clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clazz.clazz_id
     *
     * @param clazzId the value for t_clazz.clazz_id
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public void setClazzId(Integer clazzId) {
        this.clazzId = clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clazz.clazz_name
     *
     * @return the value of t_clazz.clazz_name
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public String getClazzName() {
        return clazzName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clazz.clazz_name
     *
     * @param clazzName the value for t_clazz.clazz_name
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public void setClazzName(String clazzName) {
        this.clazzName = clazzName == null ? null : clazzName.trim();
    }

    public Clazz() {
    }

    public Clazz(Integer clazzId, String clazzName) {
        this.clazzId = clazzId;
        this.clazzName = clazzName;
    }

    public Clazz(String clazzName) {
        this.clazzName = clazzName;
    }

    @Override
    public String toString() {
        return "Clazz{" +
                "clazzId=" + clazzId +
                ", clazzName='" + clazzName + '\'' +
                '}';
    }
}