package com.ssm.bean;

import java.util.Date;

public class Lend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend.serial_num
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    private Long serialNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend.book_id
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    private Long bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend.read_id
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    private Long readId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend.lend_date
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    private Date lendDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lend.back_date
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    private Date backDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend.serial_num
     *
     * @return the value of t_lend.serial_num
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public Long getSerialNum() {
        return serialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend.serial_num
     *
     * @param serialNum the value for t_lend.serial_num
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public void setSerialNum(Long serialNum) {
        this.serialNum = serialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend.book_id
     *
     * @return the value of t_lend.book_id
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend.book_id
     *
     * @param bookId the value for t_lend.book_id
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend.read_id
     *
     * @return the value of t_lend.read_id
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public Long getReadId() {
        return readId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend.read_id
     *
     * @param readId the value for t_lend.read_id
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public void setReadId(Long readId) {
        this.readId = readId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend.lend_date
     *
     * @return the value of t_lend.lend_date
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public Date getLendDate() {
        return lendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend.lend_date
     *
     * @param lendDate the value for t_lend.lend_date
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public void setLendDate(Date lendDate) {
        this.lendDate = lendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lend.back_date
     *
     * @return the value of t_lend.back_date
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public Date getBackDate() {
        return backDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lend.back_date
     *
     * @param backDate the value for t_lend.back_date
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public void setBackDate(Date backDate) {
        this.backDate = backDate;
    }

    public Lend() {
    }

    public Lend(Long bookId, Long readId, Date lendDate, Date backDate) {
        this.bookId = bookId;
        this.readId = readId;
        this.lendDate = lendDate;
        this.backDate = backDate;
    }

    public Lend(Long serialNum, Long bookId, Long readId, Date lendDate, Date backDate) {
        this.serialNum = serialNum;
        this.bookId = bookId;
        this.readId = readId;
        this.lendDate = lendDate;
        this.backDate = backDate;
    }

    @Override
    public String toString() {
        return "Lend{" +
                "serialNum=" + serialNum +
                ", bookId=" + bookId +
                ", readId=" + readId +
                ", lendDate=" + lendDate +
                ", backDate=" + backDate +
                '}';
    }
}