package com.ssm.bean;

import java.util.Date;

public class Reader {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reader.read_id
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    private Long readId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reader.name
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reader.gender
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reader.birth
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reader.phone
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reader.email
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reader.read_id
     *
     * @return the value of t_reader.read_id
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public Long getReadId() {
        return readId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reader.read_id
     *
     * @param readId the value for t_reader.read_id
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public void setReadId(Long readId) {
        this.readId = readId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reader.name
     *
     * @return the value of t_reader.name
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reader.name
     *
     * @param name the value for t_reader.name
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reader.gender
     *
     * @return the value of t_reader.gender
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reader.gender
     *
     * @param gender the value for t_reader.gender
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reader.birth
     *
     * @return the value of t_reader.birth
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reader.birth
     *
     * @param birth the value for t_reader.birth
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reader.phone
     *
     * @return the value of t_reader.phone
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reader.phone
     *
     * @param phone the value for t_reader.phone
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reader.email
     *
     * @return the value of t_reader.email
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reader.email
     *
     * @param email the value for t_reader.email
     *
     * @mbggenerated Fri Aug 12 14:39:37 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    public Reader() {
    }

    public Reader(String name, String gender, Date birth, String phone, String email) {
        this.name = name;
        this.gender = gender;
        this.birth = birth;
        this.phone = phone;
        this.email = email;
    }

    public Reader(Long readId, String name, String gender, Date birth, String phone, String email) {
        this.readId = readId;
        this.name = name;
        this.gender = gender;
        this.birth = birth;
        this.phone = phone;
        this.email = email;
    }

    @Override
    public String toString() {
        return "Reader{" +
                "readId=" + readId +
                ", name='" + name + '\'' +
                ", gender='" + gender + '\'' +
                ", birth=" + birth +
                ", phone='" + phone + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}